apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- ingress.yaml
images:
- name: alexmt/rollouts-demo
  newTag: 7fc483e0d818d4f9be22d1210373c90065ea5592
