apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- service.yaml
- ingress.yaml
images:
- name: alexmt/rollouts-demo
  newTag: 0989ffa3f7cc57b95a714f484bb2fdf8744718c3
